import type { SiteContent } from "@/lib/site-content";

export const DEFAULT_SITE_CONTENT: SiteContent = {
  hero: {
    trustedLabel: "Trusted by 50,000+ travellers worldwide",
    trustedNote: "96% approval rate",
    titlePrefix: "The smarter way to",
    titleHighlight: "apply for visas",
    description: "Apply for 150+ visas from one platform. Real-time tracking and expert support at every step.",
    searchPlaceholder: "Search a country - USA, Japan, Canada...",
    searchButtonLabel: "Search",
    popularLabel: "Popular:",
    popularCodes: ["US", "GB", "CA", "AU", "JP", "DE", "FR", "AE"],
    stats: [
      { value: "150+", label: "Countries" },
      { value: "50K+", label: "Travellers" },
      { value: "3 days", label: "Avg. delivery" },
    ],
  },
  visaCategories: {
    eyebrow: "Browse by category",
    title: "What type of visa do you need?",
    items: [
      {
        icon: "Tour",
        label: "Tourist",
        desc: "Leisure travel & holidays",
        gradient: "from-emerald-400 to-teal-500",
        bg: "bg-emerald-50 hover:bg-emerald-100 border-emerald-100",
        text: "text-emerald-700",
        query: "tourist",
      },
      {
        icon: "Work",
        label: "Work",
        desc: "Employment & work permits",
        gradient: "from-orange-400 to-amber-500",
        bg: "bg-orange-50 hover:bg-orange-100 border-orange-100",
        text: "text-orange-700",
        query: "work",
      },
      {
        icon: "Study",
        label: "Student",
        desc: "Study visas & education",
        gradient: "from-blue-400 to-indigo-500",
        bg: "bg-blue-50 hover:bg-blue-100 border-blue-100",
        text: "text-blue-700",
        query: "student",
      },
      {
        icon: "Biz",
        label: "Business",
        desc: "Meetings & conferences",
        gradient: "from-violet-400 to-purple-500",
        bg: "bg-violet-50 hover:bg-violet-100 border-violet-100",
        text: "text-violet-700",
        query: "business",
      },
    ],
  },
  countriesSection: {
    eyebrow: "Top destinations",
    title: "Where do you want to go?",
    description: "Most requested countries by our travellers",
    ctaLabel: "View all countries",
    featured: [
      { code: "US", image: "/usa.png", tag: "Most popular", tagColor: "bg-amber-100 text-amber-700" },
      { code: "GB", image: "/UK.png", tag: "Top rated", tagColor: "bg-indigo-100 text-indigo-700" },
      { code: "CA", image: "/canada.png", tag: "Trending", tagColor: "bg-emerald-100 text-emerald-700" },
      { code: "AU", image: "/australia.jpg" },
      { code: "DE", image: "/germany.png" },
      { code: "JP", image: "/japan.jpg" },
    ],
  },
  features: {
    eyebrow: "Why VisaHub",
    title: "Built for travellers, by experts",
    description: "We handle the complexity so you can focus on your journey.",
    items: [
      { icon: "Fast", title: "Apply in minutes", desc: "Our guided wizard walks you through every step. No jargon, no confusion.", color: "bg-amber-50 text-amber-600" },
      { icon: "Track", title: "Real-time tracking", desc: "See exactly where your application is from submission to approval.", color: "bg-blue-50 text-blue-600" },
      { icon: "Safe", title: "Bank-level security", desc: "Your documents and data are encrypted and protected at all times.", color: "bg-emerald-50 text-emerald-600" },
      { icon: "Team", title: "Expert support", desc: "A dedicated specialist reviews every application before submission.", color: "bg-violet-50 text-violet-600" },
      { icon: "Clear", title: "No hidden fees", desc: "The price you see is the price you pay. Transparent from day one.", color: "bg-pink-50 text-pink-600" },
      { icon: "World", title: "150+ countries", desc: "Tourist visa or work permit - we cover virtually every destination.", color: "bg-indigo-50 text-indigo-600" },
    ],
  },
  testimonials: {
    eyebrow: "Real stories",
    title: "Loved by travellers worldwide",
    description: "Real stories from people who got their visa with VisaHub.",
    summaryRating: "4.9 / 5",
    summaryLabel: "from 3,200+ reviews",
    items: [
      {
        name: "Priya Sharma",
        role: "Student, Mumbai",
        country: "US Student Visa",
        quote: "I had my F-1 approved in 12 days. The wizard walked me through every document and I never felt lost.",
        avatar: "PS",
        avatarColor: "bg-violet-100 text-violet-700",
        rating: 5,
      },
      {
        name: "Marco Bellini",
        role: "Software Engineer, Milan",
        country: "Canada Work Permit",
        quote: "The real-time tracking gave me peace of mind. I knew exactly where my application stood every day.",
        avatar: "MB",
        avatarColor: "bg-blue-100 text-blue-700",
        rating: 5,
      },
      {
        name: "Aisha Al-Rashid",
        role: "Business Owner, Dubai",
        country: "UK Business Visa",
        quote: "Transparent pricing, fast processing. My visa was ready in 8 days. Will definitely use again.",
        avatar: "AA",
        avatarColor: "bg-emerald-100 text-emerald-700",
        rating: 5,
      },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked questions",
    description: "Can't find your answer here?",
    ctaLabel: "Contact support",
    items: [
      {
        question: "How long does visa processing take?",
        answer: "Processing times vary by country and visa type - typically 3 to 21 working days. Tourist visas are usually faster, while work and student visas may take longer.",
      },
      {
        question: "Can I track my application in real time?",
        answer: "Yes. Once submitted, your dashboard shows live status updates, timeline milestones, and supplier notes at every stage of the process.",
      },
      {
        question: "What documents do I typically need?",
        answer: "Requirements differ by visa type. When you select a visa, you'll see a complete checklist of required documents. Our wizard only asks for what's needed.",
      },
      {
        question: "Are there any hidden fees?",
        answer: "Never. The price displayed includes both the government visa fee and our service fee. You'll see a full breakdown before you pay.",
      },
      {
        question: "What if my visa is rejected?",
        answer: "We'll let you know immediately and explain the reason. Depending on your supplier plan, reapplication support may be included at no extra cost.",
      },
    ],
  },
  stats: {
    items: [
      { value: "50,000+", label: "Visas processed", sub: "and counting", icon: "Docs" },
      { value: "150+", label: "Countries covered", sub: "destinations", icon: "Globe" },
      { value: "96%", label: "Approval rate", sub: "industry leading", icon: "Check" },
      { value: "3 days", label: "Fastest delivery", sub: "expedited service", icon: "Bolt" },
    ],
  },
  support: {
    phoneLabel: "Phone Support",
    phoneNumber: "1800-VFS-VISA",
    phoneHref: "tel:18008378472",
    liveChatLabel: "Live Chat",
    liveChatWait: "Average wait: 2 minutes",
    liveChatMessage: "Live chat is coming soon. Please use email support for now.",
    emailLabel: "Email Support",
    emailAddress: "support@visahub.com",
    topics: [
      "Application Status",
      "Document Upload",
      "Payment and Billing",
      "Visa Requirements",
      "Account Access",
      "Other",
    ],
    faq: [
      {
        question: "How long does visa processing take?",
        answer: "Processing time depends on country and visa type. Most tourist visas are processed within 3 to 21 working days.",
      },
      {
        question: "Can I track my application status?",
        answer: "Yes. Open My Applications to view status, timeline updates, and action items for each submission.",
      },
      {
        question: "How do I upload additional documents?",
        answer: "Go to Documents and upload files. If more documents are required, your application status will show an alert.",
      },
      {
        question: "Can I get a refund if my visa is rejected?",
        answer: "Government fees are typically non-refundable. Service fee policies vary by supplier and destination.",
      },
      {
        question: "Where can I contact support?",
        answer: "Use the ticket form below, email support@visahub.com, or call our support line during business hours.",
      },
    ],
  },
};
